In [2]:
import pandas as pd
import numpy as np

In [3]:
mma=pd.read_csv(r"F:\Universities\Offer Letters\Toronto\Datathon\mma2022_update_team_event_players_v3.csv")
mma.head()

,Unnamed: 0,Home Team Goals,Away Team Goals,Home Team Skaters,Away Team Skaters,Home Team_Boston Pride,Home Team_Buffalo Beauts,Home Team_Connecticut Whale,Home Team_Metropolitan Riveters,Home Team_Minnesota Whitecaps,...,Detail 2_Blocked,Detail 2_Missed,Detail 2_On Net,Target,Player,Player 2,Event,Home Team,Away Team,Team
0,0,0,0,5,5,0,0,0,0,1,...,0,0,0,0,Jillian Dempsey,Stephanie Anderson,Faceoff Win,Minnesota Whitecaps,Boston Pride,Boston Pride
1,1,0,0,5,5,0,0,0,0,1,...,0,0,0,1,McKenna Brand,NaN,Puck Recovery,Minnesota Whitecaps,Boston Pride,Boston Pride
2,2,0,0,5,5,0,0,0,0,1,...,0,0,0,0,McKenna Brand,Maddie Rowe,Zone Entry,Minnesota Whitecaps,Boston Pride,Boston Pride
3,3,0,0,5,5,0,0,0,0,1,...,0,0,1,1,McKenna Brand,NaN,Shot,Minnesota Whitecaps,Boston Pride,Boston Pride
4,4,0,0,5,5,0,0,0,0,1,...,0,0,0,0,Tereza Vanisova,Stephanie Anderson,Faceoff Win,Minnesota Whitecaps,Boston Pride,Boston Pride

In [4]:
mma.columns

Index(['Unnamed: 0', 'Home Team Goals', 'Away Team Goals', 'Home Team Skaters',
       'Away Team Skaters', 'Home Team_Boston Pride',
       'Home Team_Buffalo Beauts', 'Home Team_Connecticut Whale',
       'Home Team_Metropolitan Riveters', 'Home Team_Minnesota Whitecaps',
       'Home Team_Toronto Six', 'Away Team_Boston Pride',
       'Away Team_Connecticut Whale', 'Away Team_Metropolitan Riveters',
       'Away Team_Minnesota Whitecaps', 'Away Team_Toronto Six',
       'Detail 1_Backhand', 'Detail 1_Carried', 'Detail 1_Charging',
       'Detail 1_Cross-checking', 'Detail 1_Deflection', 'Detail 1_Direct',
       'Detail 1_Dumped', 'Detail 1_Elbowing', 'Detail 1_Face-off violation',
       'Detail 1_Fan', 'Detail 1_Feet', 'Detail 1_Forehand',
       'Detail 1_Game Misconduct', 'Detail 1_Goalkeeper interference',
       'Detail 1_High-sticking', 'Detail 1_Holding',
       'Detail 1_Holding the stick', 'Detail 1_Hooking',
       'Detail 1_Illegal Check to the Head', 'Detail 1_Indirect',
       'Detail 1_Interference', 'Detail 1_Lost', 'Detail 1_Played',
       'Detail 1_Retained', 'Detail 1_Roughing', 'Detail 1_Slapshot',
       'Detail 1_Slashing', 'Detail 1_Snapshot',
       'Detail 1_Too many men on the ice', 'Detail 1_Tripping',
       'Detail 1_Unsportsmanlike conduct', 'Detail 1_Wrap Around',
       'Detail 1_Wristshot', 'Detail 2_Blocked', 'Detail 2_Missed',
       'Detail 2_On Net', 'Target', 'Player', 'Player 2', 'Event', 'Home Team',
       'Away Team', 'Team'],
      dtype='object')

In [5]:
mma=mma[mma['Target']==1]
print(len(mma.Player.unique()))

126

# Goal

In [6]:
def goals(mma):
    df=pd.DataFrame()
#     for i in list (mma.Team.unique()):
#         byteam=mma[mma['Team']==i]
    shot=mma[(mma["Event"]=="Shot")|(mma["Event"]=="Goal")]
    goal=mma[(mma["Event"]=="Goal")]
    shot=shot.groupby(['Player']).count().reset_index()
    goal=goal.groupby(['Player']).count().reset_index()
    shot['total_shots']=shot['Event']
    goal['total_goal']=goal['Event']
    shot=shot[['Player','total_shots']]
    goal=goal[['Player','total_goal']]
    df1=pd.merge(mma,shot,on = "Player")
    df2=pd.merge(df1,goal, on="Player")
    df2['goal_proportion']=np.where(df2['total_goal']==0,0,df2['total_goal']/df2['total_shots'])
    df2=df2.sort_values('goal_proportion',ascending = True)
    df2['Rank_goal']=df2['goal_proportion'].rank(method='dense',ascending = True)
#     df=df.append(df2)

    df2.drop(columns=['total_goal','total_shots'],inplace=True)
    df2.reset_index(inplace=True)
    df1=df2[['Player','goal_proportion','Team','Rank_goal']]
    df1.drop_duplicates(inplace=True)
    print(df1.head())
    print(len(df1.Player.unique()))
    return df1

In [7]:
df1=goals(mma)

                      Player  goal_proportion                 Team  Rank_goal
0    Sarah-Eve Coutu Godbout         0.037037          Toronto Six        1.0
119             Jordan Juron         0.055556       Buffalo Beauts        2.0
120       Taylor Wenczkowski         0.055556         Boston Pride        2.0
387          Meghara McManus         0.062500         Boston Pride        3.0
425             Jonna Curtis         0.062500  Minnesota Whitecaps        3.0
46

<ipython-input-6-d1141596b0f3>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.drop_duplicates(inplace=True)

# Takeaway Specialist

In [8]:
def takeaway(mma):
    df=pd.DataFrame()
#     for i in list (mma.Team.unique()):
#         byteam=mma[mma['Team']==i]
    takeaway=mma[(mma["Event"]=="Takeaway")]
    takeaway=takeaway.groupby(['Player']).count().reset_index()
    takeaway['total_takeaways']=takeaway['Event']
    takeaway=takeaway[['Player','total_takeaways']]
    df2=pd.merge(mma,takeaway,on = "Player")
    df2=df2.sort_values('total_takeaways',ascending = True)
    df2['Rank_takeaway']=df2['total_takeaways'].rank(method='dense',ascending = True)
#     df=df.append(df2)

    df2.reset_index(inplace=True)
    df4=df2[['Player','total_takeaways','Team','Rank_takeaway']]
    df4.drop_duplicates(inplace=True)
    print(df4)
    return df4

In [9]:
df2=takeaway(mma)

                       Player  total_takeaways                 Team  \
0                Maeve Reilly                1    Connecticut Whale
1             Victoria Hanson                1         Boston Pride
18                Lynn Astrup                2  Minnesota Whitecaps
19                Sara Bustad                2  Minnesota Whitecaps
38          Nicole Guagliardo                2    Connecticut Whale
...                       ...              ...                  ...
10087        Natalie Marcuzzi               23          Toronto Six
10289      Marie-Jo Pelletier               24       Buffalo Beauts
10478  Breanne Wilson-Bennett               25          Toronto Six
10645          Alyson Matteau               28       Buffalo Beauts
10840        Dominique Kremer               29       Buffalo Beauts

       Rank_takeaway
0                1.0
1                1.0
18               2.0
19               2.0
38               2.0
...              ...
10087           23.0
10289           24.0
10478           25.0
10645           26.0
10840           27.0

[114 rows x 4 columns]

<ipython-input-8-658703809da8>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4.drop_duplicates(inplace=True)

# Original Dataframe

In [10]:
data=pd.read_csv(r"F:\Universities\Offer Letters\Toronto\Datathon\Rotman MMA Summer Datathon NWHL.csv")
data.head()

,game_date,Home Team,Away Team,Period,Clock,Home Team Skaters,Away Team Skaters,Home Team Goals,Away Team Goals,Team,...,Event,X Coordinate,Y Coordinate,Detail 1,Detail 2,Detail 3,Detail 4,Player 2,X Coordinate 2,Y Coordinate 2
0,23-01-2021,Minnesota Whitecaps,Boston Pride,1,20:00,5,5,0,0,Boston Pride,...,Faceoff Win,100,43,Backhand,NaN,NaN,NaN,Stephanie Anderson,NaN,NaN
1,23-01-2021,Minnesota Whitecaps,Boston Pride,1,19:58,5,5,0,0,Boston Pride,...,Puck Recovery,107,40,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,23-01-2021,Minnesota Whitecaps,Boston Pride,1,19:57,5,5,0,0,Boston Pride,...,Zone Entry,125,28,Carried,NaN,NaN,NaN,Maddie Rowe,NaN,NaN
3,23-01-2021,Minnesota Whitecaps,Boston Pride,1,19:55,5,5,0,0,Boston Pride,...,Shot,131,28,Snapshot,On Net,t,f,NaN,NaN,NaN
4,23-01-2021,Minnesota Whitecaps,Boston Pride,1,19:53,5,5,0,0,Boston Pride,...,Faceoff Win,169,21,Backhand,NaN,NaN,NaN,Stephanie Anderson,NaN,NaN

# Passer

In [11]:
def passer(data):
    df=pd.DataFrame()
#     for i in list (data.Team.unique()):
#         byteam=data[data['Team']==i]
    passes=data[(data["Event"]=="Play")|(data["Event"]=="Incomplete Play")]
    play=data[(data["Event"]=="Play")]
    passes=passes.groupby(['Player']).count().reset_index()
    play=play.groupby(['Player']).count().reset_index()
    passes['total_passes']=passes['Event']
    play['successful_passes']=play['Event']
    passes=passes[['Player','total_passes']]
    play=play[['Player','successful_passes']]
    df1=pd.merge(data,passes,on = "Player")
    df2=pd.merge(df1,play, on="Player")
    df2['pass_proportion']=np.where(df2['successful_passes']==0,0,df2['successful_passes']/df2['total_passes'])
    df2=df2.sort_values('pass_proportion',ascending = True)
    df2['Rank_pass']=df2['pass_proportion'].rank(method='dense',ascending = True)
#     df=df.append(df2)
    
    df2.reset_index(inplace=True)
    df2.drop(columns=['successful_passes','total_passes'],inplace=True)
    df2=df2[['Player','pass_proportion','Team','Rank_pass']]
    df2.drop_duplicates(inplace=True)
    print(df2.tail())
    return df2

In [12]:
df3=passer(data)

                   Player  pass_proportion            Team  Rank_pass
26678     Lovisa Selander         0.958333    Boston Pride      111.0
26724       Carly Jackson         0.960784  Buffalo Beauts      112.0
26834  Samantha Ridgewell         1.000000     Toronto Six      113.0
26837     Victoria Hanson         1.000000    Boston Pride      113.0
26859          Caty Flagg         1.000000  Buffalo Beauts      113.0

# Faceoff Wins

In [13]:
def faceoff_wins(data):
    df=pd.DataFrame()
#     for i in list (data.Team.unique()):
#         byteam=data[data['Team']==i]
    faceoff=data[(data["Event"]=="Faceoff Win")]
    faceoff=faceoff.groupby(['Player']).count().reset_index()
    faceoff['total_wins']=faceoff['Event']
    faceoff=faceoff[['Player','total_wins']]
    df2=pd.merge(data,faceoff,on = "Player")
    df2=df2.sort_values('total_wins',ascending = True)
    df2['Rank_faceoffWin']=df2['total_wins'].rank(method='dense',ascending = True)
#     df=df.append(df2)

    df3=df2[['Player','total_wins','Team','Rank_faceoffWin']]
    df3.drop_duplicates(inplace=True)
#     df3.reset_index(inplace=True)
    print(df3.tail())
    return df3

In [14]:
df4=faceoff_wins(data)

                 Player  total_wins            Team  Rank_faceoffWin
5941       Jordan Juron          49  Buffalo Beauts             22.0
1065    Tereza Vanisova          51    Boston Pride             23.0
3525        Lexie Laing          55    Boston Pride             24.0
218     Jillian Dempsey          70    Boston Pride             25.0
8890  Shiann Darkangelo          79     Toronto Six             26.0

<ipython-input-13-e6beaee62297>:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3.drop_duplicates(inplace=True)

# Faceoff Losses

In [15]:
def faceoff_loss(data):
    df=pd.DataFrame()
    faceoff=data[(data["Event"]=="Faceoff Win")]
    faceoff=faceoff.groupby(['Player 2']).count().reset_index()
    faceoff['total_losses']=faceoff['Event']
    faceoff=faceoff[['Player 2','total_losses']]
    df2=pd.merge(data,faceoff,left_on = "Player", right_on='Player 2')
#     for i in list (df2.Team.unique()):
#         byteam=df2[df2['Team']==i]
    df2=df2.sort_values('total_losses',ascending = True)
    df2['Rank_faceoffLoss']=df2['total_losses'].rank(method='dense',ascending = False)
#     df=df.append(byteam)

    df3=df2[['Player','total_losses','Team','Rank_faceoffLoss']]
    df3.drop_duplicates(inplace=True)
#     df3.reset_index(inplace=True)
    print(df3.head())
    return df3

In [16]:
df5=faceoff_loss(data)

                   Player  total_losses                   Team  \
11008        Taylor Woods             1            Toronto Six
7380        Amanda Conway             1      Connecticut Whale
1949   Taylor Wenczkowski             1           Boston Pride
11173     Mallory Rushton             1  Metropolitan Riveters
11272     Theresa Knutson             1  Metropolitan Riveters

       Rank_faceoffLoss
11008              30.0
7380               30.0
1949               30.0
11173              30.0
11272              30.0

<ipython-input-15-c71a6d82bb27>:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3.drop_duplicates(inplace=True)

In [17]:
data1=data.copy()
data1=data1[['Player','Team']]
df9=pd.merge(df1,data1,how='right')
df6=pd.merge(df9,df2,on=['Player','Team'],how='left')
df7=pd.merge(df6,df3,on=['Player','Team'],how='left')
df8=pd.merge(df7,df4,on=['Player','Team'],how='left')
final_df=pd.merge(df8,df5,on=['Player','Team'],how='left')
# final_df=final_df.drop(columns=['index','index_x','index_y'])
final_df.drop_duplicates(inplace=True)
# final_df.to_excel('final.xlsx')
final_df.head()

,Player,goal_proportion,Team,Rank_goal,total_takeaways,Rank_takeaway,pass_proportion,Rank_pass,total_wins,Rank_faceoffWin,total_losses,Rank_faceoffLoss
0,Jillian Dempsey,0.176471,Boston Pride,18.0,22.0,22.0,0.689655,64.0,70.0,25.0,27.0,13.0
1,McKenna Brand,0.115385,Boston Pride,12.0,7.0,7.0,0.806818,103.0,6.0,6.0,6.0,25.0
4,Tereza Vanisova,NaN,Boston Pride,NaN,17.0,17.0,0.797688,101.0,51.0,23.0,26.0,14.0
5,Samantha Davis,0.173913,Boston Pride,17.0,18.0,18.0,0.712575,76.0,5.0,5.0,3.0,28.0
6,Stephanie Anderson,NaN,Minnesota Whitecaps,NaN,19.0,19.0,0.696970,69.0,38.0,20.0,52.0,2.0

In [18]:
len(final_df)

126

In [19]:
final_df['Rank_goal']=final_df['Rank_goal'].fillna(0)
final_df['Rank_takeaway']=final_df['Rank_takeaway'].fillna(0)
final_df['Rank_pass']=final_df['Rank_pass'].fillna(0)
final_df['Rank_faceoffWin']=final_df['Rank_faceoffWin'].fillna(0)
final_df['Rank_faceoffLoss']=final_df['Rank_faceoffLoss'].fillna(0)
final_df.to_excel('ranks_v.xlsx')

PermissionError: [Errno 13] Permission denied: 'ranks_v.xlsx'